<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="OJO-PC" ignored="0" tests="1" failures="1" timestamp="29 Jul 2018 14:54:05 GMT" time="23.349" errors="0">
  <testcase name="feature" time="22.552" classname="TestRunner">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: expected [https://app.brighthr.com/dashboard] but found [https://app.brighthr.com/login]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: expected [https://app.brighthr.com/dashboard] but found [https://app.brighthr.com/login]
at cucumber.api.testng.TestNGCucumberRunner.runCucumber(TestNGCucumberRunner.java:69)
at TestRunner.feature(TestRunner.java:29)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: expected [https://app.brighthr.com/dashboard] but found [https://app.brighthr.com/login]
at stepdefs.loginpage.iAmOnMyProflePage(loginpage.java:54)
at âœ½.Then I am on my profle page(loginpage.feature:12)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- feature -->
</testsuite>
